'use client';
import {useState,useRef,useEffect} from 'react';
import {Upload,Loader2,FileCheck2,X,ArrowRight,Search} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import type {ImportedJob,JobLink} from '@/lib/rolebridge/job-source';
import {toast} from 'sonner';
export function SourceImporter({onBatch,onCandidates}:{onBatch:(jobs:ImportedJob[])=>void;onCandidates:(links:JobLink[])=>void}){
 const [url,setUrl]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[failures,setFailures]=useState<{url:string;message:string}[]>([]),[next,setNext]=useState<string|null>(null);
 const controller=useRef<AbortController|null>(null),collected=useRef<ImportedJob[]>([]),seen=useRef(new Set<string>()),candidates=useRef(new Map<string,JobLink>()),alive=useRef(true);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;controller.current?.abort();};},[]);
 async function request(link:string,kind:'job'|'search',signal:AbortSignal){const response=await fetch('/api/import-jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:link,mode:kind}),signal});const data=await response.json() as {error?:string;job?:ImportedJob;links?:JobLink[];nextPage?:string|null};if(!response.ok)throw new Error(data.error||'페이지를 읽지 못했어요.');return data;}
 async function run(resume=false){if(!url.trim()&&!resume)return;controller.current?.abort();const c=new AbortController();controller.current=c;setBusy(true);setError('');if(!resume){collected.current=[];seen.current.clear();setFailures([]);setNext(null);candidates.current.clear();onCandidates([]);onBatch([]);}try{
 let page=resume?next:'https://www.saramin.co.kr/zf_user/search/recruit?searchword='+encodeURIComponent(url.trim());let pageCount=0,attempted=0;const bad:{url:string;message:string}[]=[];
 while(page&&pageCount<5&&!c.signal.aborted){pageCount++;setMessage(`검색 ${pageCount}페이지의 공고 링크를 찾고 있어요…`);const currentPage=page;const data=await request(page,'search',c.signal);for(const link of data.links||[])candidates.current.set(link.url,link);onCandidates([...candidates.current.values()]);const links=(data.links||[]).filter(x=>!seen.current.has(x.url));if(!links.length){setNext(null);page=null;break;}setNext(data.nextPage||null);
 for(const link of links){if(c.signal.aborted){setNext(currentPage);break;}attempted++;setMessage(`${pageCount}페이지 · ${attempted}개 확인 중 · ${collected.current.length}개 본문 수집`);try{const detail=await request(link.url,'job',c.signal);if(detail.job){collected.current.push(detail.job);onBatch([...collected.current]);}seen.current.add(link.url);}catch(e){if(c.signal.aborted){setNext(currentPage);break;}seen.current.add(link.url);bad.push({url:link.url,message:e instanceof Error?e.message:'가져오기 실패'});setFailures(p=>[...p,bad[bad.length-1]]);}}
 page=c.signal.aborted?currentPage:data.nextPage||null;
 }
 if(!c.signal.aborted)setMessage(`${collected.current.length}개 본문 수집 · 이번 실행 실패 ${bad.length}개${page?' · 다음 묶음이 있어요.':' · 현재 공개 검색 범위를 확인했어요.'}`);
 }catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'공고를 가져오지 못했어요.');}finally{if(alive.current){setBusy(false);if(c.signal.aborted)setMessage(`수집을 중단했어요. 가져온 ${collected.current.length}개는 비교할 수 있어요.`);}}}
 return <div className="source-import"><form onSubmit={e=>{e.preventDefault();void run();}}><label htmlFor="job-search">직무 또는 키워드</label><div className="url-input-wrap"><Search size={18}/><Input id="job-search" type="search" maxLength={80} value={url} onChange={e=>setUrl(e.target.value)} disabled={busy} placeholder="AX, PM, FDE… 어떤 일을 찾고 있나요?"/></div><div className="search-suggestions">{['AX','PM','FDE','서비스 기획','프론트엔드'].map(word=><button key={word} type="button" disabled={busy} onClick={()=>setUrl(word)}>{word}</button>)}</div><Button type="submit" variant="outline" className="import-button" disabled={busy||!url.trim()}>{busy?<Loader2 className="animate-spin"/>:<Search/>}채용공고 검색하기<ArrowRight/></Button></form><p className="field-hint">사람인 공개 검색결과를 가져와요. 최대 5페이지씩 살펴보고 다음 결과도 이어서 검색할 수 있어요.</p>{busy&&<Button variant="ghost" size="sm" onClick={()=>controller.current?.abort()}><X/>수집 중단</Button>}{message&&<p className="import-status" role="status">{message}</p>}{error&&<p className="error-message" role="alert">{error}</p>}{!busy&&next&&<Button variant="outline" className="mt-3" onClick={()=>run(true)}>다음 검색결과 이어서 가져오기</Button>}{failures.length>0&&<details className="import-failures"><summary>본문을 가져오지 못한 공고 {failures.length}개</summary>{failures.map((f,i)=><p key={i}><a href={f.url} target="_blank" rel="noreferrer">공고 직접 열기 ↗</a><br/>{f.message}</p>)}</details>}</div>;
}
export function ResumeUpload({onText}:{onText:(text:string,name:string)=>void}){
 const [busy,setBusy]=useState(false),[name,setName]=useState(''),[error,setError]=useState('');const fileRef=useRef<HTMLInputElement>(null);
 async function read(file:File){setBusy(true);setError('');try{if(file.size>8*1024*1024)throw new Error('8MB 이하 파일을 올려주세요.');let text='';const ext=file.name.split('.').pop()?.toLowerCase();const bytes=await file.arrayBuffer();
 if(ext==='pdf'){const pdfjs=await import('pdfjs-dist');pdfjs.GlobalWorkerOptions.workerSrc='/vendor/pdf.worker.min.mjs';const loading=pdfjs.getDocument({data:bytes,useSystemFonts:true});const doc=await loading.promise;try{if(doc.numPages>40)throw new Error('40페이지 이하 이력서를 올려주세요.');const parts:string[]=[];for(let p=1;p<=doc.numPages;p++){const page=await doc.getPage(p);const content=await page.getTextContent();parts.push(content.items.map(item=>'str'in item?item.str+('hasEOL'in item&&item.hasEOL?'\n':' '):'').join(''));page.cleanup();}text=parts.join('\n\n');}finally{await loading.destroy();}}
 else if(ext==='docx'){const mammoth=await import('mammoth');const result=await mammoth.extractRawText({arrayBuffer:bytes});text=result.value;}
 else if(ext==='txt'||ext==='md'){text=new TextDecoder().decode(bytes);}
 else throw new Error('PDF, DOCX, TXT, MD 파일을 지원해요. HWP·이미지는 PDF나 DOCX로 변환해 주세요.');
 text=text.trim();if(text.length<30)throw new Error('읽을 수 있는 텍스트가 부족해요. 스캔·이미지 PDF는 텍스트가 있는 PDF로 변환해 주세요.');if(text.length>14000)throw new Error('이력서 내용이 14,000자를 넘어요. 경력·프로젝트 중심으로 줄여주세요.');onText(text,file.name);setName(file.name);toast.success('이력서를 읽었어요. 추출 내용은 아래에서 확인할 수 있어요.');
 }catch(e){setError(e instanceof Error?e.message:'이력서를 읽지 못했어요. 암호화 여부와 파일 형식을 확인해 주세요.');}finally{setBusy(false);if(fileRef.current)fileRef.current.value='';}}
 return <div className="resume-upload"><input ref={fileRef} type="file" accept=".pdf,.docx,.txt,.md" className="sr-only" aria-label="이력서 파일 업로드" onChange={e=>{const f=e.target.files?.[0];if(f)void read(f);}}/><button className="upload-zone" type="button" disabled={busy} onClick={()=>fileRef.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy&&e.dataTransfer.files[0])void read(e.dataTransfer.files[0]);}}>{busy?<Loader2 className="animate-spin"/>:name?<FileCheck2/>:<Upload/>}<strong>{busy?'이력서의 경험을 읽고 있어요…':name||'이력서를 놓거나 클릭해 주세요'}</strong><span>PDF · DOCX · TXT · MD / 최대 8MB</span></button><p className="field-hint">파일은 브라우저에서 읽어요. 서버에 저장하지 않아요. 연락처 등 불필요한 정보는 추출 내용에서 지워주세요.</p>{error&&<p className="error-message" role="alert">{error}</p>}</div>;
}
