"use client";
import { useState,useEffect,useRef,useMemo } from 'react';
import {usePathname,useRouter} from 'next/navigation';
import { flushSync } from 'react-dom';
import { ArrowUpRight,ArrowRight,Layers3,Sparkles,FileText,Compass,Check,ShieldCheck,Download,Copy,ChevronDown,Plus,Loader2,Scale,Info,MessageCircle,Target,ExternalLink,Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Input } from '@/components/ui/input';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Progress } from '@/components/ui/progress';
import { Toaster } from '@/components/ui/sonner';
import { toast } from 'sonner';
import { analyzeLocal } from '@/lib/rolebridge/engine';
import { inputSchema,validateEvidence,metrics,statusLabels,importanceLabels,weights,type Analysis,type AnalysisInput,type Requirement,type Report } from '@/lib/rolebridge/model';
import { sampleInput,sampleExperience } from '@/lib/rolebridge/samples';
import { SourceImporter,ResumeUpload } from '@/components/rolebridge-import';
import type { ImportedJob,JobLink } from '@/lib/rolebridge/job-source';
import { fullPrompt } from '@/lib/rolebridge/prompts';
const first=sampleInput();
const initial:Analysis={input:first,report:analyzeLocal(first),engine:'local',createdAt:''};
const levelNames={entry:'신입 공고',experienced:'경력 공고',mixed:'신입·경력 공고',unknown:'연차 확인 필요'};
function download(name:string,body:string,type='text/plain'){const url=URL.createObjectURL(new Blob([body],{type:`${type};charset=utf-8`}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
async function copy(text:string){try{await navigator.clipboard.writeText(text);toast.success('복사했어요.');}catch{toast.error('복사 권한이 없어요. 내려받기를 이용해 주세요.');}}
function reportText(a:Analysis){const m=metrics(a.report.requirements);return `# ${a.report.title}\n\n${a.report.summary}\n\n분석 방식: ${a.engine==='ai'?'AI 분석':'문장 규칙 기반 기본 분석'}\n확인한 역량 일치도: ${m.match===null?'미산정':m.match+'%'} / 판정 가능 비율: ${m.coverage}%\n전체 요구 역량 범위: ${m.lower}–${m.upper}% (합격 확률이 아님)\n\n## 요구 역량과 근거\n${a.report.requirements.map(r=>`### ${r.skill} · ${importanceLabels[r.importance]} · ${statusLabels[r.status]}\n공고: ${r.jobQuote}\n경험: ${r.evidenceQuote||'미확인'}\n판단: ${r.reason}\n확인 질문: ${r.question}\n보완 과제: ${r.task}\n결과물: ${r.deliverable}`).join('\n\n')}\n\n## 지원 조건\n${a.report.conditions.map(c=>`${c.label}: ${c.status} — ${c.reason}`).join('\n')}\n\n## 도메인 탐색 가설\n${a.report.domains.map(d=>`### ${d.domain}\n${d.reason}\n근거: ${d.evidenceQuote}\n확인할 점: ${d.caveat}\n실험: ${d.experiment}`).join('\n\n')}\n\n## 이력서 표현\n${a.report.resume.map(r=>`원문: ${r.before}\n제안: ${r.after}\n추가 질문: ${r.question}`).join('\n\n')}\n\n## 한계\n${a.report.limitations.join('\n')}\n\n점수 계산: 필수 3, 주요 업무 2, 우대 1. 근거 확인 1, 일부 확인 0.5, 보완 필요 0. 미확인은 일치도 분모에서 제외하고 판정 가능 비율에 반영.`;}
export default function RoleBridgeWorkflow({children}:{children:React.ReactNode}){
 const pathname=usePathname();const router=useRouter();const step=pathname==='/resume'?'resume':pathname==='/results'?'results':'jobs';
 function go(next:'jobs'|'resume'|'results'){router.push('/'+next);window.scrollTo({top:0,behavior:'smooth'});}
 const [input,setInput]=useState<AnalysisInput>({...first,job:'',experience:''}),[analysis,setAnalysis]=useState<Analysis|null>(null),[isSample,setIsSample]=useState(false),[tab,setTab]=useState('skills');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[aiAvailable,setAiAvailable]=useState(false),[modal,setModal]=useState<'prompt'|'method'|'compare'|'ai'|null>(null),[promptTab,setPromptTab]=useState('use'),[json,setJson]=useState(''),[importError,setImportError]=useState('');
 const [candidates,setCandidates]=useState<JobLink[]>([]),[collecting,setCollecting]=useState(false);
 const [imported,setImported]=useState<ImportedJob[]>([]),[sourceUrl,setSourceUrl]=useState(''),[resumeName,setResumeName]=useState('');
 const [saved,setSaved]=useState<Analysis[]>([]),[question,setQuestion]=useState<Requirement|null>(null),[answer,setAnswer]=useState('');
 const inputRef=useRef(input);inputRef.current=input;const analysisRef=useRef(analysis);analysisRef.current=analysis;const mounted=useRef(true);
 useEffect(()=>{mounted.current=true;fetch('/api/analyze').then(r=>r.json() as Promise<{available:boolean}>).then(v=>{if(mounted.current)setAiAvailable(v.available===true);}).catch(()=>{});return()=>{mounted.current=false;};},[]);
 function patch(value:Partial<AnalysisInput>){setInput(p=>({...p,...value}));setError('');}
 function completeLocal(raw:unknown,fromTool=false){const parsed=inputSchema.safeParse(raw);if(!parsed.success)throw new Error(parsed.error.issues[0]?.message||'입력을 확인해 주세요.');const next:Analysis={input:parsed.data,report:analyzeLocal(parsed.data),engine:'local',createdAt:new Date().toISOString()};if(fromTool)flushSync(()=>{setInput(parsed.data);setAnalysis(next);setIsSample(false);setTab('skills');setError('');});else{setAnalysis(next);setIsSample(false);setTab('skills');setError('');}go('results');return next;}
 useEffect(()=>{
  type Context={registerTool:(tool:{name:string;title:string;description:string;inputSchema:object;annotations:object;execute:(value:unknown)=>unknown},options:{signal:AbortSignal})=>void|Promise<void>};
  const ctx=(document as Document&{modelContext?:Context}).modelContext;if(!ctx)return;const lifecycle=new AbortController();
  const tools=[{name:'analyze_job_fit',title:'공고와 경험 기본 분석',description:'공고와 실제 경험을 문장 규칙으로 분석하고 화면을 갱신합니다. 외부 AI에 전송하지 않습니다. 결과는 합격 확률이 아닙니다.',inputSchema:{type:'object',properties:{job:{type:'string',minLength:40,maxLength:16000},experience:{type:'string',maxLength:14000},career:{type:'string',enum:['entry','experienced']},years:{type:['number','null']},role:{type:'string'}},required:['job','experience','career','years','role'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:(value:unknown)=>{const a=completeLocal(value,true);return {title:a.report.title,engine:a.engine,metrics:metrics(a.report.requirements),requirements:a.report.requirements};}},{name:'read_fit_report',title:'현재 분석 결과 읽기',description:'화면에 표시된 공고 분석과 근거를 읽습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>analysisRef.current?{...analysisRef.current.report,engine:analysisRef.current.engine,metrics:metrics(analysisRef.current.report.requirements)}:{status:'empty'}}];
  for(const tool of tools){try{void Promise.resolve(ctx.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}
  return()=>lifecycle.abort();
 },[]);
 async function analyze(engine:'local'|'ai',override?:AnalysisInput){const raw=override||(!input.job.trim()&&batch.length?{...input,job:batch[0].job.text}:input);if(raw.job!==input.job){setInput(raw);setSourceUrl(batch[0]?.job.url||'');}setError('');if(engine==='local'){try{if(raw.job.trim().length<40&&candidates.length){if(batch.length){const selected={...raw,job:batch[0].job.text};setInput(selected);setSourceUrl(batch[0].job.url);completeLocal(selected);}else{setAnalysis(null);go('results');}return;}completeLocal(raw);toast.success('공고와 경험을 연결했어요.');}catch(e){setError(e instanceof Error?e.message:'입력을 확인해 주세요.');}return;}const parsed=inputSchema.safeParse(raw);if(!parsed.success){setError(parsed.error.issues[0].message);return;}setBusy(true);try{const response=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(parsed.data),signal:AbortSignal.timeout(65000)});const data=await response.json() as {error?:string;report:unknown};if(!response.ok)throw new Error(data.error||'AI 분석에 실패했어요.');const report=validateEvidence(data.report,parsed.data);setAnalysis({report,input:parsed.data,engine:'ai',createdAt:new Date().toISOString()});setIsSample(false);setTab('skills');setModal(null);go('results');toast.success('AI 분석을 완료했어요.');}catch(e){setError(e instanceof Error&&e.name==='TimeoutError'?'분석 시간이 길어지고 있어요. 잠시 후 다시 시도해 주세요.':e instanceof Error?e.message:'AI 연결을 확인해 주세요.');}finally{setBusy(false);}}
 const batch=useMemo(()=>imported.map(job=>{const data={...input,job:job.text};let report:Report;try{report=analyzeLocal(data);}catch{report={title:job.title,summary:'이 공고는 현재 분석으로 판단하지 못했어요.',seniority:'unknown',requirements:[],conditions:[],domains:[],resume:[],limitations:['이 공고의 자동 분석에 실패해 점수를 산정하지 않았습니다. 다른 공고의 비교는 계속 진행합니다.']};}return {job,analysis:{input:data,report,engine:'local' as const,createdAt:job.fetchedAt},metrics:metrics(report.requirements)};}).sort((a,b)=>b.metrics.lower-a.metrics.lower),[imported,input.experience,input.career,input.years]);
 const promptInput=!input.job.trim()&&batch.length?{...input,job:batch[0].job.text}:input;
 const m=analysis?metrics(analysis.report.requirements):null;const dirty=!!analysis&&JSON.stringify(input)!==JSON.stringify(analysis.input);
 const counts=useMemo(()=>{const a={met:0,partial:0,gap:0,unknown:0};analysis?.report.requirements.forEach(r=>a[r.status]++);return a;},[analysis]);
 function addCompare(){if(!analysis)return;if(saved.some(s=>s.input.job===analysis.input.job&&s.input.experience===analysis.input.experience)){toast.info('이미 비교함에 담은 결과예요.');setModal('compare');return;}if(saved.length>=3){toast.info('한 번에 3개 공고를 비교할 수 있어요. 비교함에서 하나를 지워주세요.');setModal('compare');return;}setSaved(p=>[...p,analysis]);toast.success('비교함에 담았어요. 다른 공고를 분석해 함께 살펴보세요.');}
 function importResult(){try{const parsed=inputSchema.parse(promptInput);const body=JSON.parse(json.replace(/^```(?:json)?\s*/,'').replace(/\s*```$/,''));const report=validateEvidence(body.report||body,parsed);setInput(parsed);setAnalysis({input:parsed,report,engine:'ai',createdAt:new Date().toISOString()});setIsSample(false);setTab('skills');setModal(null);setImportError('');setJson('');go('results');toast.success('원문 인용을 확인하고 AI 결과를 불러왔어요.');}catch(e){setImportError(e instanceof SyntaxError?'JSON 형식을 확인해 주세요. 설명 문장 없이 JSON 전체를 붙여넣어 주세요.':e instanceof Error&&e.message.startsWith('공고')?e.message:'출력 형식 또는 원문 근거가 맞지 않습니다. 현재 공고와 경험으로 만든 프롬프트를 사용해 주세요.');}}
 return <>{children}<Toaster position="bottom-center" theme="light"/><header className="topbar"><a href="/" className="brand" aria-label="RoleBridge 홈"><span className="brand-icon"><Layers3 size={22}/></span>rolebridge<span className="beta">BETA</span></a><span className="top-caption">공고에서 시작하는 커리어</span><Button variant="ghost" className="demo-button" onClick={()=>{setInput(first);setAnalysis(initial);setIsSample(true);go('results');}}>샘플 체험</Button><Button variant="ghost" onClick={()=>setModal('compare')}><Scale/>비교함<span className="counter">{saved.length}</span></Button><Button variant="outline" onClick={()=>setModal('prompt')}><FileText/><span>분석 프롬프트</span></Button></header>
 <main className={`workspace step-workspace step-${step}`}><nav className="step-navigation" aria-label="분석 단계">{([{id:'jobs',name:'공고 검색',number:'01'},{id:'resume',name:'이력서 연결',number:'02'},{id:'results',name:'가능성 발견',number:'03'}] as const).map((s,i)=><div key={s.id}><button type="button" aria-current={step===s.id?'step':undefined} disabled={s.id==='resume'&&!input.job.trim()&&!imported.length||s.id==='results'&&!analysis&&!imported.length} onClick={()=>go(s.id)}><span className="step-nav-number">{s.number}</span><span>{s.name}</span></button>{i<2&&<span className="step-line"/>}</div>)}</nav><div className="page-heading"><div><div className="eyebrow">{step==='jobs'?'START WITH THE OPPORTUNITY':step==='resume'?'CONNECT YOUR EXPERIENCE':'YOUR NEXT POSSIBILITY'}</div><h1>{step==='jobs'?'어떤 일을 찾고 있나요?':step==='resume'?'해온 일을 알려주세요.':'경험 너머의 가능성을 발견했어요.'}</h1><p>{step==='jobs'?'AX, PM, FDE… 원티드 공고를 하나씩 읽고 이력서와 연결할 준비를 해드려요.':step==='resume'?'이력서 하나면 충분해요. 신입이라면 프로젝트 경험도 좋아요.':'공고가 찾는 역량과 내 경험의 근거를 함께 살펴보세요.'}</p></div></div>
 <div className="workgrid"><section className="input-panel step-panel" hidden={step!=='jobs'}><div className="panel-heading"><h2><Compass size={19}/>관심 있는 일 검색하기</h2><span className="tiny-pill">01</span></div><SourceImporter onBusy={setCollecting} onBatch={jobs=>{setImported(jobs);setIsSample(false);}} onCandidates={links=>{setCandidates(links);if(!links.length){patch({job:''});setAnalysis(null);setSourceUrl('');}}}/>
 {input.job.trim()&&<div className="selected-job"><span className="quote-label">선택한 공고</span><strong>{input.job.split('\n')[0]}</strong><span>{input.job.length.toLocaleString()}자 · {sourceUrl?'원티드에서 자동으로 읽은 본문':'가상 예시'}</span></div>}{candidates.length>0&&<div className="selected-job"><span className="quote-label">가져온 검색결과</span><strong>원티드 공고 {candidates.length}개 발견 · 비교 준비 {imported.length}개</strong><span>{collecting?'확인된 공고부터 이력서와 비교할 수 있어요. 나머지는 계속 읽어둘게요.':'공고 확인을 마쳤어요. 이력서를 연결하면 바로 비교할 수 있어요.'}</span></div>}{candidates.length>0&&<div className="search-preview-list">{imported.map(c=><a href={c.url} target="_blank" rel="noreferrer" key={c.url}><span><strong>{c.title}</strong><small>{c.company} · {c.summary}</small></span><ExternalLink size={14}/></a>)}</div>}<div className="step-bottom"><span>다음은, 내 경험을 연결할 차례예요.</span><Button disabled={!input.job.trim()&&!imported.length} onClick={()=>go('resume')}>이력서 연결하기<ArrowRight/></Button></div></section>
 <section className="input-panel step-panel" hidden={step!=='resume'}><div className="panel-heading experience-heading"><h2>나의 경험</h2><span className="tiny-pill">02</span></div><ResumeUpload onText={(text,name)=>{patch({experience:text});setResumeName(name);setIsSample(false);}}/><div className="career-fields"><div><label htmlFor="career">나의 경력 단계</label><Select value={input.career} onValueChange={v=>patch({career:v as AnalysisInput['career']})} disabled={busy}><SelectTrigger id="career" className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="entry">신입 · 첫 커리어</SelectItem><SelectItem value="experienced">경력 · 다음 커리어</SelectItem></SelectContent></Select></div>{input.career==='experienced'&&<div><label htmlFor="years">업무 경력 (년)</label><Input id="years" type="number" min="0" max="60" step="0.5" placeholder="미입력" value={input.years??''} onChange={e=>patch({years:e.target.value===''?null:Number(e.target.value)})}/></div>}</div><p className="field-hint">{input.career==='entry'?'수업·동아리·개인 프로젝트도 좋아요. 본인이 한 일과 만든 결과물을 알려주세요.':'공고가 요구하는 업무에서 맡은 역할, 책임 범위와 결과를 알려주세요.'}</p><details className="manual-input"><summary>{resumeName?`추출한 이력서 확인 · 수정 (${input.experience.length.toLocaleString()}자)`:"경험 직접 입력 · 샘플 경험 보기"}<ChevronDown size={15}/></summary><button className="text-action sample-experience" type="button" onClick={()=>patch({experience:sampleExperience})}>샘플 경험 불러오기</button><label htmlFor="experience" className="sr-only">직접 수행한 경험 또는 이력서 내용</label><Textarea id="experience" value={input.experience} maxLength={14000} disabled={busy} onChange={e=>patch({experience:e.target.value})} className="experience-input" placeholder="예: 동아리에서 사용자 8명을 인터뷰하고 문제를 정리했습니다. 요구사항 문서와 프로토타입을 직접 만들었습니다."/><p className="field-hint">경험은 나중에 적어도 돼요. 먼저 공고와 확인 질문을 볼 수 있어요.</p></details>
 {error&&<p role="alert" className="error-message">{error}</p>}<Button className="analyze-button" disabled={busy} onClick={()=>analyze('local')}><Layers3/>공고와 내 경험 분석하기<ArrowRight/></Button><div className="mode-note">기본 분석 · 문장 규칙으로 바로 확인</div><Button variant="outline" className="ai-button" disabled={busy} onClick={()=>setModal('ai')}>{busy?<Loader2 className="animate-spin"/>:<Sparkles/>}{busy?'AI가 공고와 경험을 읽고 있어요…':'AI로 문맥까지 분석하기'}{!aiAvailable&&<span>연결 안내</span>}</Button><p className="privacy-note"><ShieldCheck size={13}/>기본 분석은 브라우저 안에서 처리해요.</p><p className="storage-note">새로고침하면 입력·비교함이 지워져요. 결과는 내려받아 보관하세요.</p><div className="step-back"><Button variant="ghost" onClick={()=>go('jobs')}>← 공고 검색으로 돌아가기</Button></div></section>
 <section className="result-panel step-results" hidden={step!=='results'} aria-busy={busy}><div className="result-navigation"><Button variant="ghost" onClick={()=>go('resume')}>← 이력서 수정</Button><Button variant="outline" onClick={()=>go('jobs')}><Plus/>다른 공고 검색하기</Button></div><div className="result-top"><div><span className="eyebrow">FIT REPORT</span><h2>경험 너머의 가능성</h2></div><span className="sample-label">{analysis?.input.job===first.job&&analysis?.input.experience===first.experience?'가상 공고 · 샘플 경험':analysis?.engine==='ai'?'AI 분석 결과':'기본 분석'}</span></div>
 {candidates.length>0&&<div className="batch-results report-card"><div className="card-heading"><h3>원티드 공고 {batch.length}개 비교</h3><span className="status partial">이력서와 자동 대조</span></div><p className="tab-description">{input.experience===sampleExperience?'현재 샘플 경험으로 비교 중이에요. 내 이력서를 올려주세요.':'현재 입력한 경험으로 비교했어요.'} 전체 역량 중 근거가 확인된 가중치 비율순이에요. 공고별 기준과 필수 조건을 함께 확인하세요.</p><div className="batch-list">{batch.map((b,i)=><button type="button" className="batch-row" key={b.job.url} onClick={()=>{setInput(b.analysis.input);setAnalysis(b.analysis);setSourceUrl(b.job.url);setIsSample(false);setTab('skills');}}><span className="batch-index">{String(i+1).padStart(2,'0')}</span><span className="batch-title"><strong>{b.job.title}</strong><span>{b.job.source} · {b.metrics.coverage}% 판정 가능{b.analysis.report.conditions.some(c=>c.status==='fail')?' · 필수 연차 확인 필요':''}</span></span><span className="batch-score">{b.metrics.match===null?'미산정':`${b.metrics.lower}%`}<small>확인된 비율</small></span><ArrowUpRight size={15}/></button>)}</div><p className="field-hint">{collecting?'다른 원티드 공고도 하나씩 읽고 있어요. 확인되는 대로 비교 결과에 추가해요.':'상세 공고를 읽어낸 결과만 비교했어요. 마감되었거나 확인하지 못한 공고는 자동 제외했어요.'}</p></div>}
 {!analysis?<div className="empty-report"><Compass size={40}/><h3>{collecting?'원티드 공고를 하나씩 읽고 있어요.':batch.length?'비교할 공고를 선택해 주세요.':'관심 있는 공고에서 시작하세요.'}</h3><p>{collecting?'주요 업무와 자격 요건을 확인하고 있어요. 읽어낸 공고부터 자동으로 비교해요.':batch.length?'위 공고를 선택하면 역량과 경험의 연결을 자세히 볼 수 있어요.':'검색어만 입력하면 공고 확인은 서비스가 맡을게요.'}</p><Button variant="outline" onClick={()=>go('jobs')}>공고 검색하기<ArrowRight/></Button></div>:<>{dirty&&<div className="stale-note"><Info size={16}/>입력이 바뀌었어요. 아래는 이전 입력의 결과예요. 다시 분석해 주세요.</div>}
 <div className="fit-hero"><div className="hero-copy"><span className="hero-label">{analysis.report.title.replace('[가상 공고] ','')}</span><h3>{counts.met>0?<>내가 해온 일에서,<br/>다음 가능성을 찾았어요.</>:<>공고가 원하는 일,<br/>경험으로 하나씩 연결해요.</>}</h3><p>{analysis.report.summary}</p><span className="hero-chip"><Check size={14}/>{levelNames[analysis.report.seniority]} · {analysis.input.career==='entry'?'신입 경험 기준':'경력 경험 기준'}</span></div><div className="score-circle"><strong>{m?.match??'—'}{m?.match!==null&&<span>%</span>}</strong><span>확인한 역량 일치도</span></div></div>
 <div className="coverage-bar"><div><span>판정 가능 비율 <strong>{m?.coverage}%</strong></span><button type="button" className="text-action" onClick={()=>setModal('method')}>어떻게 계산하나요? <Info size={13}/></button></div><Progress value={m?.coverage} aria-label="판정 가능 비율"/><p>추출한 요구 역량 중 근거로 판단할 수 있는 비율이에요. 합격 확률을 뜻하지 않아요.</p></div>
 <div className="report-actions"><div className="metric-pills"><span><i className="met-dot"/>확인 {counts.met}</span><span>일부 {counts.partial}</span><span>보완 {counts.gap}</span><span>미확인 {counts.unknown}</span></div><div><Button variant="ghost" size="sm" onClick={addCompare}><Plus/>비교</Button><Button variant="ghost" size="sm" onClick={()=>download('rolebridge-report.md',reportText(analysis),'text/markdown')} aria-label="현재 분석 결과 내려받기"><Download/></Button></div></div>
 <Tabs value={tab} onValueChange={setTab} className="report-tabs"><TabsList className="report-tab-list" variant="line"><TabsTrigger value="skills">역량 연결</TabsTrigger><TabsTrigger value="actions">보완 계획</TabsTrigger><TabsTrigger value="domains">도메인 탐색</TabsTrigger><TabsTrigger value="resume">이력서</TabsTrigger></TabsList>
 <TabsContent value="skills"><div className="report-card"><div className="card-heading"><h3>공고가 찾는 역량, 내가 가진 근거</h3><span className="field-hint">{analysis.report.requirements.length}개 항목</span></div>{analysis.report.requirements.length===0?<div className="inline-empty">평가할 IT 역량을 찾지 못했어요. 다른 공고를 선택하거나 AI 프롬프트를 사용해 주세요.</div>:analysis.report.requirements.map(r=><details className="skill-detail" key={r.id}><summary><div><strong>{r.skill}</strong><span className="importance">{importanceLabels[r.importance]}</span><p>{r.evidenceQuote||'입력한 경험에서 근거를 찾지 못했어요'}</p></div><span className={`status ${r.status}`}>{statusLabels[r.status]}</span><ChevronDown size={15}/></summary><div className="evidence-detail"><span className="quote-label">공고 원문</span><blockquote>{r.jobQuote}</blockquote><span className="quote-label">내 경험 원문</span><blockquote>{r.evidenceQuote||'아직 확인되지 않았어요.'}</blockquote><p>{r.reason}</p>{r.status!=='met'&&<><p className="question-copy"><MessageCircle size={15}/>{r.question}</p><Button variant="outline" size="sm" onClick={()=>{setQuestion(r);setAnswer('');}}>이 경험에 답변하기</Button></>}</div></details>)}</div>
 {analysis.report.conditions.length>0&&<div className="conditions report-card"><h3>스킬과 별도로 확인할 지원 조건</h3>{analysis.report.conditions.map((c,i)=><div key={i}><strong>{c.label}</strong><span className={`status ${c.status==='pass'?'met':c.status==='fail'?'gap':'unknown'}`}>{c.status==='pass'?'조건 충족':c.status==='fail'?'조건 불충족':'확인 필요'}</span><p>{c.reason}</p><blockquote>{c.jobQuote}</blockquote></div>)}</div>}
 {analysis.report.domains.length>0&&<button className="domain-teaser" type="button" onClick={()=>setTab('domains')}><span className="domain-icon"><Compass/></span><span><span className="eyebrow">BEYOND YOUR EXPERIENCE</span><strong>아직 일해보지 않은 도메인도, 가능성이 있어요.</strong><span className="domain-preview">{analysis.report.domains.map(x=>x.domain).join(' · ')}</span></span><ArrowUpRight/></button>}</TabsContent>
 <TabsContent value="actions"><div className="report-card"><div className="card-heading"><h3>다음 행동을 작게, 구체적으로</h3><Target size={19}/></div><p className="tab-description">미확인은 경험을 먼저 확인하고, 부족한 역량은 결과물을 만들며 채워보세요.</p>{analysis.report.requirements.filter(r=>r.status!=='met').sort((a,b)=>weights[b.importance]-weights[a.importance]).map((r,i)=><div className="action-card" key={r.id}><span className="step-number">{String(i+1).padStart(2,'0')}</span><div><div className="action-title"><h4>{r.skill}</h4><span className={`status ${r.status}`}>{r.status==='unknown'?'경험 확인부터':statusLabels[r.status]}</span></div><p>{r.status==='unknown'?r.question:r.task}</p>{r.status!=='unknown'&&<div className="deliverable"><FileText size={15}/><span>남길 결과물: {r.deliverable}</span></div>}<Button variant="ghost" size="sm" onClick={()=>{setQuestion(r);setAnswer('');}}>{r.status==='unknown'?'경험 답변하기':'완료한 경험 추가하기'}<ArrowRight/></Button></div></div>)}{Object.values(counts).slice(1).every(x=>x===0)&&<p className="inline-empty">추출된 역량에 관련 근거가 있어요. 각 근거의 범위와 공고의 요구 수준을 다시 확인해 보세요.</p>}</div></TabsContent>
 <TabsContent value="domains"><div className="report-card"><div className="card-heading"><h3>해보지 않은 분야로, 경험 넓히기</h3><Compass size={19}/></div><p className="tab-description">아래는 경험의 전이 가능성에 대한 가설이에요. 채용 중인 공고 목록이나 검증된 추천은 아니에요.</p>{analysis.report.domains.length?analysis.report.domains.map((d,i)=><article className="domain-card" key={i}><div className="domain-heading"><span>0{i+1}</span><h3>{d.domain}</h3><ArrowUpRight size={18}/></div><p>{d.reason}</p><span className="quote-label">연결한 경험</span><blockquote>{d.evidenceQuote}</blockquote><p className="caveat">{d.caveat}</p><div className="experiment"><Compass size={17}/><div><strong>작게 확인해 보기</strong><p>{d.experiment}</p></div></div></article>):<p className="inline-empty">전이 가능한 역량을 찾으려면 구체적인 경험이 필요해요. 직접 한 행동과 결과물을 추가해 주세요.</p>}</div></TabsContent>
 <TabsContent value="resume"><div className="report-card"><div className="card-heading"><h3>해온 일을, 공고가 이해하는 말로</h3><FileText size={19}/></div><p className="tab-description">{analysis.engine==='local'?'기본 분석에서는 확인된 경험을 간결한 문장으로 정리해요. 공고 맥락에 맞춘 재작성은 AI 분석·프롬프트를 이용해 주세요.':'원문 근거로 작성한 AI 초안이에요. 사용 전 도구·역할·성과가 실제 경험과 일치하는지 확인해 주세요.'}</p>{analysis.report.resume.length?analysis.report.resume.map((r,i)=><div className="resume-card" key={i}><span className="quote-label">나의 원문</span><p className="before">{r.before}</p><span className="quote-label blue">이렇게 정리해 보세요</span><p className="after">{r.after}</p><p className="resume-question">{r.question}</p><Button variant="outline" size="sm" onClick={()=>copy(r.after)}><Copy/>문장 복사</Button></div>):<p className="inline-empty">구체적인 수행 경험을 먼저 알려주세요. 없는 경력이나 성과를 대신 만들어 쓰지 않아요.</p>}</div></TabsContent></Tabs>
 <details className="limitations"><summary><ShieldCheck size={14}/>{analysis.engine==='local'?'기본 분석의 범위와 한계':'AI 분석의 범위와 한계'}<ChevronDown size={14}/></summary><ul>{analysis.report.limitations.map((l,i)=><li key={i}>{l}</li>)}</ul></details></>}
 </section></div><footer>rolebridge <span>가능성은, 공고와 경험 사이에 있습니다.</span><span>Wanted AI Championship 2026 프로젝트</span></footer></main>
 <Dialog open={modal==='prompt'} onOpenChange={o=>!o&&setModal(null)}><DialogContent className="wide-dialog"><DialogHeader><DialogTitle>공고에서 출발하는 분석 프롬프트</DialogTitle><DialogDescription>현재 공고와 경험을 포함한 프롬프트를 원하는 AI에 사용하고, JSON 결과를 이 화면으로 가져올 수 있어요.</DialogDescription></DialogHeader><Tabs value={promptTab} onValueChange={setPromptTab}><TabsList><TabsTrigger value="use">프롬프트 사용</TabsTrigger><TabsTrigger value="import">AI 결과 가져오기</TabsTrigger></TabsList><TabsContent value="use"><div className="prompt-principles"><span>공고 먼저</span><span>신입·경력 구분</span><span>원문 근거 필수</span><span>성과 창작 금지</span></div><label htmlFor="prompt-text">분석 프롬프트 + 현재 입력</label><Textarea id="prompt-text" readOnly value={fullPrompt(promptInput)} className="prompt-text"/><p className="field-hint">외부 AI에 붙여넣기 전 연락처·실명 등 불필요한 개인정보를 지워주세요.</p><div className="dialog-actions"><Button onClick={()=>copy(fullPrompt(promptInput))}><Copy/>입력 포함 복사</Button><Button variant="outline" onClick={()=>download('rolebridge-prompt.md',fullPrompt(promptInput),'text/markdown')}><Download/>내려받기</Button></div><details className="prompt-explanation"><summary>분석을 설계한 방식</summary><p>요구 사항 추출 → 경험의 근거 연결 → 미확인 분리 → 도메인 전이 가설 → 실행 과제 → 사실만 사용하는 이력서 표현. 점수는 모델이 아닌 프로그램이 계산합니다.</p></details></TabsContent><TabsContent value="import"><label htmlFor="json-result">AI가 반환한 JSON 전체</label><Textarea id="json-result" className="prompt-text" maxLength={100000} value={json} onChange={e=>{setJson(e.target.value);setImportError('');}} placeholder={'{"title": "...", "summary": "...", "requirements": [...]}'}/><p className="field-hint">현재 입력과 인용을 대조해 확인해요. 다른 공고의 결과는 불러올 수 없어요.</p>{importError&&<p role="alert" className="error-message">{importError}</p>}<Button className="mt-4" onClick={importResult} disabled={!json.trim()}>근거 확인하고 결과 보기<ArrowRight/></Button></TabsContent></Tabs></DialogContent></Dialog>
 <Dialog open={modal==='method'} onOpenChange={o=>!o&&setModal(null)}><DialogContent><DialogHeader><DialogTitle>점수보다 중요한 건, 근거예요.</DialogTitle><DialogDescription>이 수치는 합격 확률이 아닌 설명 가능한 MVP 분석 지표예요.</DialogDescription></DialogHeader><div className="method-content"><h3>확인한 역량 일치도</h3><p>근거 확인 1점, 일부 확인 0.5점, 보완 필요 0점. 필수는 3배, 주요 업무는 2배, 우대는 1배로 계산해요. 미확인 항목은 분모에서 제외해요.</p><h3>판정 가능 비율</h3><p>전체 추출 역량의 가중치 중 판단할 수 있는 가중치의 비율이에요. 이 값이 낮으면 높은 일치도도 충분한 근거가 있다고 보기 어려워요.</p><h3>전체 역량 범위 {m?.lower}–{m?.upper}%</h3><p>미확인을 모두 0점 또는 모두 1점으로 가정한 범위예요. 미확인이 ‘부족하다’는 뜻은 아니에요. 필수 연차는 이 점수와 별도로 확인해요.</p><p className="caveat">공고마다 기준이 달라 점수만으로 순위를 단정할 수 없어요. 기본 분석은 사전에 등록된 역량만 추출하며, 자기 보고의 실제 수행 수준은 추가 확인이 필요해요.</p></div></DialogContent></Dialog>
 <Dialog open={modal==='compare'} onOpenChange={o=>!o&&setModal(null)}><DialogContent className="wide-dialog"><DialogHeader><DialogTitle>관심 공고, 나란히 비교하기</DialogTitle><DialogDescription>최대 3개를 비교할 수 있어요. 점수뿐 아니라 미확인 항목과 필수 조건을 함께 보세요. 새로고침하면 비워져요.</DialogDescription></DialogHeader>{saved.length===0?<div className="inline-empty">아직 담은 공고가 없어요. 분석 결과의 ‘+ 비교’를 눌러 담아보세요.</div>:<div className="compare-grid">{saved.map((s,i)=>{const sm=metrics(s.report.requirements);return <article className="compare-card" key={i}><div><span className="eyebrow">0{i+1}</span><Button variant="ghost" size="icon-sm" aria-label={`${s.report.title} 비교함에서 삭제`} onClick={()=>setSaved(p=>p.filter((_,j)=>j!==i))}><Trash2/></Button></div><h3>{s.report.title}</h3><strong className="compare-score">{sm.match??'—'}{sm.match!==null?'%':''}</strong><span>확인한 역량 일치도</span><p>판정 가능 비율 <strong>{sm.coverage}%</strong></p><p>필수 조건 불충족 {s.report.conditions.filter(c=>c.status==='fail').length}개</p><p>미확인 역량 {s.report.requirements.filter(r=>r.status==='unknown').length}개</p><p className="field-hint">{s.engine==='ai'?'AI 분석':'기본 분석'} · {s.input.career==='entry'?'신입':'경력'}</p><Button variant="outline" onClick={()=>{setInput(s.input);setAnalysis(s);setIsSample(false);setModal(null);go('results');}}>결과 다시 보기</Button></article>;})}</div>}<p className="field-hint">공정하게 비교하려면 같은 경험과 경력 단계로 분석하세요.</p></DialogContent></Dialog>
 <Dialog open={modal==='ai'} onOpenChange={o=>!o&&!busy&&setModal(null)}><DialogContent><DialogHeader><DialogTitle>문맥을 읽는 AI 분석</DialogTitle><DialogDescription>{aiAvailable?'공고의 실제 요구 수준과 경험의 맥락을 함께 읽어요.':'현재 AI API가 연결되어 있지 않아요. 프롬프트를 다른 AI에서 실행하고 결과를 가져올 수 있어요.'}</DialogDescription></DialogHeader><div className="ai-info"><Sparkles size={27}/><p>신입·경력의 기대 수준, 다른 도메인으로 전이 가능한 역량, 사실에 근거한 이력서 표현까지 분석해요.</p></div>{aiAvailable?<><p className="field-hint">분석을 시작하면 현재 공고·경험·경력 단계가 OpenAI로 전송됩니다. 불필요한 개인정보를 삭제해 주세요. 서비스는 입력을 데이터베이스에 저장하지 않으며 제공사의 데이터 정책이 적용됩니다.</p>{error&&<p role="alert" className="error-message">{error}</p>}<Button disabled={busy} onClick={()=>analyze('ai')}>{busy?<Loader2 className="animate-spin"/>:<Sparkles/>}입력 전송하고 AI 분석하기</Button></>:<Button onClick={()=>{setPromptTab('use');setModal('prompt');}}>프롬프트 복사·결과 가져오기<ArrowRight/></Button>}<a className="external-link" href="https://platform.openai.com/docs/guides/your-data" target="_blank" rel="noreferrer">OpenAI 데이터 처리 안내<ExternalLink size={13}/></a></DialogContent></Dialog>
 <Dialog open={!!question} onOpenChange={o=>!o&&setQuestion(null)}><DialogContent><DialogHeader><DialogTitle>{question?.skill} 경험 확인</DialogTitle><DialogDescription>{question?.question}</DialogDescription></DialogHeader><label htmlFor="answer">내가 직접 해본 일</label><Textarea id="answer" value={answer} maxLength={3000} onChange={e=>setAnswer(e.target.value)} className="answer-input" placeholder="상황 → 내가 한 행동 → 만든 결과물 순서로 적어주세요. 경험이 없거나 학습 중이라면 그대로 알려주세요."/><p className="field-hint">답변은 기존 경험 아래에 추가돼요. 실제로 해본 내용만 적어주세요.</p><Button disabled={!answer.trim()} onClick={()=>{const next={...input,experience:`${input.experience}\n${question?.skill}: ${answer.trim()}`};const parsed=inputSchema.safeParse(next);if(!parsed.success){toast.error('경험은 14,000자 이내로 작성해 주세요.');return;}setInput(next);setQuestion(null);void analyze('local',next);}}>답변 반영·기본 재분석<ArrowRight/></Button></DialogContent></Dialog>
 </>;
}
